import type { AppData } from "@/types/domain";

export const demoData: AppData = {
  business: {
    id: "demo-business",
    name: "LM Lavage de Vitres",
    currency: "CAD",
    timezone: "America/Toronto",
    gstEnabled: false,
    qstEnabled: false,
    gstRate: 0.05,
    qstRate: 0.09975,
    defaultFollowupMonths: 12,
    digestEmail: "proprietaire@lm-lavage.ca",
  },
  clients: [
    {
      id: "client-marie",
      clientNumber: 1,
      name: "Marie-Pier",
      phone: "819 555-0142",
      email: "marie.pier@example.com",
      notes: null,
      needsReview: false,
      properties: [
        {
          id: "property-marie",
          clientId: "client-marie",
          address: "262 rue de la Galère",
          city: "Gatineau",
          province: "QC",
          postalCode: null,
        },
      ],
    },
    {
      id: "client-kevin",
      clientNumber: 2,
      name: "Kevin",
      phone: "819 555-0188",
      email: null,
      notes: null,
      needsReview: false,
      properties: [
        {
          id: "property-kevin",
          clientId: "client-kevin",
          address: "15 rue du Chaland",
          city: "Gatineau",
          province: "QC",
          postalCode: null,
        },
      ],
    },
    {
      id: "client-josee",
      clientNumber: 3,
      name: "Josée",
      phone: "819 555-0115",
      email: "josee@example.com",
      notes: "Prévenir avant d’arriver.",
      needsReview: false,
      properties: [
        {
          id: "property-josee",
          clientId: "client-josee",
          address: "14 rue des Hêtres",
          city: "Gatineau",
          province: "QC",
          postalCode: null,
        },
      ],
    },
    {
      id: "client-review",
      clientNumber: 4,
      name: "Client à confirmer",
      phone: null,
      email: null,
      notes: "Nom absent du classeur importé.",
      needsReview: true,
      properties: [
        {
          id: "property-review",
          clientId: "client-review",
          address: "49 rue Jean-Marc",
          city: "Gatineau",
          province: "QC",
          postalCode: null,
        },
      ],
    },
    {
      id: "client-marcel",
      clientNumber: 5,
      name: "Marcel",
      phone: "819 555-0199",
      email: null,
      notes: null,
      needsReview: false,
      properties: [
        {
          id: "property-marcel",
          clientId: "client-marcel",
          address: "161 rue Fernand-Arvisais",
          city: "Gatineau",
          province: "QC",
          postalCode: null,
        },
      ],
    },
  ],
  workers: [
    { id: "worker-alexis", name: "Alexis", active: true, salesSplitProfile: "standard", userId: null },
    { id: "worker-guillaume", name: "Guillaume", active: true, salesSplitProfile: "standard", userId: null },
    { id: "worker-po", name: "P-O", active: true, salesSplitProfile: "po_sale", userId: null },
  ],
  jobs: [
    {
      id: "job-1",
      clientId: "client-marie",
      propertyId: "property-marie",
      clientName: "Marie-Pier",
      address: "262 rue de la Galère, Gatineau",
      startsAt: "2026-04-26T09:00:00-04:00",
      endsAt: "2026-04-26T11:00:00-04:00",
      timeIsSet: true,
      status: "completed",
      paymentStatus: "paid",
      serviceScope: "both",
      windowCount: 18,
      serviceSubtotal: 100,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 100,
      tipAmount: 0,
      paidAt: "2026-04-26T11:00:00-04:00",
      paymentMethod: "Virement Interac",
      followupDate: null,
      notes: null,
      workerIds: ["worker-alexis", "worker-guillaume"],
      sellerWorkerId: "worker-alexis",
      sellerName: "Alexis",
      googleSyncStatus: "synced",
    },
    {
      id: "job-2",
      clientId: "client-kevin",
      propertyId: "property-kevin",
      clientName: "Kevin",
      address: "15 rue du Chaland, Gatineau",
      startsAt: "2026-05-03T09:00:00-04:00",
      endsAt: "2026-05-03T11:30:00-04:00",
      timeIsSet: true,
      status: "completed",
      paymentStatus: "paid",
      serviceScope: "both",
      windowCount: 24,
      serviceSubtotal: 150,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 150,
      tipAmount: 0,
      paidAt: "2026-05-03T11:30:00-04:00",
      paymentMethod: "Comptant",
      followupDate: "2027-05-03",
      notes: null,
      workerIds: ["worker-alexis", "worker-guillaume"],
      sellerWorkerId: "worker-guillaume",
      sellerName: "Guillaume",
      googleSyncStatus: "synced",
    },
    {
      id: "job-3",
      clientId: "client-josee",
      propertyId: "property-josee",
      clientName: "Josée",
      address: "14 rue des Hêtres, Gatineau",
      startsAt: "2026-05-30T09:00:00-04:00",
      endsAt: "2026-05-30T11:00:00-04:00",
      timeIsSet: true,
      status: "completed",
      paymentStatus: "paid",
      serviceScope: "outside",
      windowCount: 20,
      serviceSubtotal: 130,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 130,
      tipAmount: 20,
      paidAt: "2026-05-30T11:00:00-04:00",
      paymentMethod: "Comptant",
      followupDate: "2027-05-30",
      notes: null,
      workerIds: ["worker-alexis"],
      sellerWorkerId: "worker-alexis",
      sellerName: "Alexis",
      googleSyncStatus: "synced",
    },
    {
      id: "job-4",
      clientId: "client-review",
      propertyId: "property-review",
      clientName: "Client à confirmer",
      address: "49 rue Jean-Marc, Gatineau",
      startsAt: "2026-05-30T12:30:00-04:00",
      endsAt: "2026-05-30T14:00:00-04:00",
      timeIsSet: true,
      status: "completed",
      paymentStatus: "paid",
      serviceScope: "outside",
      windowCount: 14,
      serviceSubtotal: 100,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 100,
      tipAmount: 10,
      paidAt: "2026-05-30T14:00:00-04:00",
      paymentMethod: "Comptant",
      followupDate: "2027-05-30",
      notes: "Nom du client à confirmer.",
      workerIds: ["worker-guillaume"],
      sellerWorkerId: "worker-guillaume",
      sellerName: "Guillaume",
      googleSyncStatus: "synced",
    },
    {
      id: "job-5",
      clientId: "client-marcel",
      propertyId: "property-marcel",
      clientName: "Marcel",
      address: "161 rue Fernand-Arvisais, Gatineau",
      startsAt: "2026-05-30T15:00:00-04:00",
      endsAt: "2026-05-30T17:00:00-04:00",
      timeIsSet: true,
      status: "completed",
      paymentStatus: "paid",
      serviceScope: "both",
      windowCount: 19,
      serviceSubtotal: 120,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 120,
      tipAmount: 0,
      paidAt: "2026-05-30T17:00:00-04:00",
      paymentMethod: "Virement Interac",
      followupDate: "2027-05-30",
      notes: null,
      workerIds: ["worker-alexis", "worker-guillaume"],
      sellerWorkerId: "worker-alexis",
      sellerName: "Alexis",
      googleSyncStatus: "synced",
    },
    {
      id: "job-6",
      clientId: "client-josee",
      propertyId: "property-josee",
      clientName: "Josée",
      address: "14 rue des Hêtres, Gatineau",
      startsAt: "2026-06-18T08:00:00-04:00",
      endsAt: "2026-06-18T10:00:00-04:00",
      timeIsSet: true,
      status: "scheduled",
      paymentStatus: "unpaid",
      serviceScope: "outside",
      windowCount: 20,
      serviceSubtotal: 135,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 135,
      tipAmount: 0,
      paidAt: null,
      paymentMethod: null,
      followupDate: "2027-06-18",
      notes: null,
      workerIds: ["worker-alexis"],
      sellerWorkerId: "worker-alexis",
      sellerName: "Alexis",
      googleSyncStatus: "synced",
    },
    {
      id: "job-7",
      clientId: "client-marcel",
      propertyId: "property-marcel",
      clientName: "Marcel",
      address: "161 rue Fernand-Arvisais, Gatineau",
      startsAt: "2026-06-18T12:00:00-04:00",
      endsAt: "2026-06-18T14:00:00-04:00",
      timeIsSet: true,
      status: "scheduled",
      paymentStatus: "unpaid",
      serviceScope: "both",
      windowCount: 19,
      serviceSubtotal: 125,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 125,
      tipAmount: 0,
      paidAt: null,
      paymentMethod: null,
      followupDate: "2027-06-18",
      notes: null,
      workerIds: ["worker-guillaume"],
      sellerWorkerId: "worker-guillaume",
      sellerName: "Guillaume",
      googleSyncStatus: "pending",
    },
    {
      id: "job-8",
      clientId: "client-marie",
      propertyId: "property-marie",
      clientName: "Marie-Pier",
      address: "262 rue de la Galère, Gatineau",
      startsAt: "2026-06-19T09:30:00-04:00",
      endsAt: "2026-06-19T11:30:00-04:00",
      timeIsSet: true,
      status: "scheduled",
      paymentStatus: "unpaid",
      serviceScope: "both",
      windowCount: 18,
      serviceSubtotal: 110,
      gstAmount: 0,
      qstAmount: 0,
      totalDue: 110,
      tipAmount: 0,
      paidAt: null,
      paymentMethod: null,
      followupDate: "2027-06-19",
      notes: null,
      workerIds: ["worker-alexis", "worker-guillaume"],
      sellerWorkerId: "worker-po",
      sellerName: "P-O",
      googleSyncStatus: "synced",
    },
  ],
  expenses: [
    {
      id: "expense-1",
      date: "2026-04-26",
      vendor: "Starter Kit",
      category: "Équipement",
      subtotal: 192.93,
      gstAmount: 0,
      qstAmount: 0,
      total: 192.93,
      paymentMethod: null,
      notes: "Importé du classeur initial.",
      jobId: null,
      receiptPath: null,
    },
    {
      id: "expense-2",
      date: "2026-05-24",
      vendor: "Nouveau Pole Set",
      category: "Équipement",
      subtotal: 63.22,
      gstAmount: 0,
      qstAmount: 0,
      total: 63.22,
      paymentMethod: null,
      notes: "Importé du classeur initial.",
      jobId: null,
      receiptPath: null,
    },
    {
      id: "expense-3",
      date: "2026-05-30",
      vendor: "Microfibres et scrubber",
      category: "Fournitures",
      subtotal: 37.9,
      gstAmount: 0,
      qstAmount: 0,
      total: 37.9,
      paymentMethod: null,
      notes: "Importé du classeur initial.",
      jobId: null,
      receiptPath: null,
    },
  ],
  canvassingVisits: [
    "rue des Hêtres",
    "rue Jean-Marc",
    "rue Tony",
    "rue des Abricotiers",
    "rue des Pommetiers",
  ].map((street, index) => ({
    id: `visit-${index + 1}`,
    street,
    city: "Gatineau",
    visitedAt: `2026-05-${String(20 + index).padStart(2, "0")}`,
    outcome: index < 2 ? "Clients obtenus" : "Rue visitée",
    notes: null,
    revisitDate: `2027-05-${String(20 + index).padStart(2, "0")}`,
  })),
  allocationBuckets: [
    { id: "bucket-alexis", name: "Alexis", type: "person", percentage: 40, poSalePercentage: 35, amount: 240 },
    { id: "bucket-guillaume", name: "Guillaume", type: "person", percentage: 40, poSalePercentage: 35, amount: 240 },
    { id: "bucket-gas", name: "Gaz", type: "reserve", percentage: 20, poSalePercentage: 15, amount: 120 },
    { id: "bucket-po", name: "P-O", type: "person", percentage: 0, poSalePercentage: 15, amount: 0 },
  ],
  revenueSeries: [
    { month: "Jan", current: 0, previous: 0 },
    { month: "Fév", current: 0, previous: 0 },
    { month: "Mars", current: 0, previous: 0 },
    { month: "Avr", current: 100, previous: 0 },
    { month: "Mai", current: 500, previous: 0 },
    { month: "Juin", current: 0, previous: 0 },
  ],
};
